### ISSUE TITLE
can you supply the auth and traffic sql  structure？

### ISSUE THREAD

**Issue by cssailing** [idle-user/api.idleuser.com#33]
thanks for your share project.
i have try to learn slim to build an api
can you supply the auth and traffic sql  structure, for demo use the project in localhost?

**Comment by idle-user** [comment]
> thanks for your share project. i have try to learn slim to build an api can you supply the auth and traffic sql structure, for demo use the project in localhost?

Hi there. Thanks for taking interest in my project.
I will update the README and maybe add a db-init file in the future that includes the db table structures in the future - but to get you started I have added screenshots that may help. Let me know if there are any questions or if this is enough help.

**Auth Table**
![image](https://user-images.githubusercontent.com/15640986/146964493-0193d20d-cbfa-4ac6-bf11-d331a4390959.png)

I call a stored procedure inside the auth repository. Here's the query.

```sql
CREATE PROCEDURE `usp_api_ins_auth`(
    IN in_uid INT(11) UNSIGNED,
    IN in_token BINARY(32)
)
BEGIN

    DECLARE t_now DATETIME;
    DECLARE t_exp DATETIME;
    DECLARE t_access INT;
    
    SELECT NOW() INTO t_now;
    SELECT t_now + INTERVAL 1 YEAR INTO t_exp;
    SELECT access INTO t_access FROM `user` WHERE id=in_uid;

    INSERT INTO `api_auth` 
        (auth_token, auth_token_exp, access_level, user_id, created, last_updated) 
    VALUES 
        (in_token, t_exp, t_access, in_uid, t_now, t_now) 
    ON DUPLICATE KEY UPDATE
        auth_token=in_token,
        auth_token_exp=t_exp,
        access_level=t_access,
        last_updated=t_now;

END
```


**Traffic Tables**
This one is a bit more convoluted as I attempted to normalize the data.

![image](https://user-images.githubusercontent.com/15640986/146970298-abf2214e-3d02-4172-a961-d0174bf1c52e.png)
![image](https://user-images.githubusercontent.com/15640986/146970314-9c64619f-7240-419c-b6a9-982898d6a3d9.png)
![image](https://user-images.githubusercontent.com/15640986/146970325-e07d700c-c829-4902-b65c-b81d0bb760d7.png)
![image](https://user-images.githubusercontent.com/15640986/146970332-251bc85e-9b21-4560-be0a-f241370f793e.png)

Like the auth example above, I used a stored procedure to insert.
This one is a bit longer as it uses all the tables above.
```sql
CREATE PROCEDURE `usp_traffic_ins`(
    IN in_request TEXT,
    IN in_user_agent TEXT,
    IN in_ip TEXT,
    IN in_auth_user_id INT
)
BEGIN
	
    DECLARE t_now DATETIME;
    DECLARE t_id CHAR(36);
    DECLARE t_request_id BINARY(16);
    DECLARE t_user_agent_id BINARY(16);
    DECLARE t_ip_id BINARY(16);
    
    SELECT NOW() INTO t_now;
    
    
    INSERT INTO `traffic_request` 
        (id, request, md5hash, created, last_accessed, access_cnt) 
    VALUES 
        (UUID_TO_BIN(UUID()), in_request, UNHEX(MD5(in_request)), t_now, t_now, 1) 
    ON DUPLICATE KEY UPDATE 
        last_accessed=t_now, 
        access_cnt=access_cnt+1;
    SELECT id INTO t_request_id FROM `traffic_request` WHERE md5hash=UNHEX(MD5(in_request));

    
    INSERT INTO `traffic_user_agent` 
        (id, user_agent, md5hash, created, last_accessed, access_cnt) 
    VALUES 
        (UUID_TO_BIN(UUID()), in_user_agent, UNHEX(MD5(in_user_agent)), t_now, t_now, 1) 
    ON DUPLICATE KEY UPDATE 
        last_accessed=t_now,
        access_cnt=access_cnt+1;
    SELECT id INTO t_user_agent_id FROM `traffic_user_agent` WHERE md5hash=UNHEX(MD5(in_user_agent));
    
    INSERT INTO `traffic_ip` 
        (id, ip, created, last_accessed, access_cnt) 
    VALUES 
        (UUID_TO_BIN(UUID()), INET6_ATON(in_ip), t_now, t_now, 1) 
    ON DUPLICATE KEY UPDATE 
        last_accessed=t_now,
        access_cnt=access_cnt+1;
    SELECT id INTO t_ip_id FROM `traffic_ip` WHERE ip=INET6_ATON(in_ip);
    
    SELECT UUID() INTO t_id;

    INSERT INTO `traffic`
        (id, request_id, user_agent_id, ip_id, auth_user_id, created)
    VALUES
        (UUID_TO_BIN(t_id), t_request_id, t_user_agent_id, t_ip_id, in_auth_user_id, t_now);
        
        
    SELECT t_id AS `uuid`, `traffic`.* FROM `traffic` WHERE id=UUID_TO_BIN(t_id);
    
END
```

**Comment by cssailing** [comment]
thank you

**Comment by cssailing** [comment]
macos 12.0.1

**Comment by cssailing** [comment]
macos 12.1
mysql 8.0.24

test for traffic，throw error
"error": {
        "type": "SERVER_ERROR",
        "description": "SQLSTATE[42000]: Syntax error or access violation: 1172 Result consisted of more than one row"
    }

**Comment by idle-user** [comment]
> macos 12.1 mysql 8.0.24
> 
> test for traffic，throw error "error": { "type": "SERVER_ERROR", "description": "SQLSTATE[42000]: Syntax error or access violation: 1172 Result consisted of more than one row" }

Strange. I never ran into that issue. Do you know which line in the SP is causing it?
Maybe a table's column isn't set it up properly? (Unique?)

**Comment by idle-user** [comment]
> test for traffic，throw error "error": { "type": "SERVER_ERROR", "description": "SQLSTATE[42000]: Syntax error or access violation: 1172 Result consisted of more than one row" }

I understand this is a late reply. But I have begun to *Dockerize* the project repo.
Documentation details will come soon, but if you're familiar with docker, docker-compose will bootstrap everything.

Future updates will also include migration to PHP8 and further normalization of existing database tables.
